import { getPool } from "./db";

/**
 * Postgres (Neon) schema for Bizurado — the cloud equivalent of the old
 * better-sqlite3 initSchema. Differences from the SQLite version, by design:
 *
 *  - Fresh cloud DB, so ALL columns are declared up-front (no PRAGMA/ALTER
 *    migrations, no dedupe passes — the UNIQUE constraints prevent dupes from
 *    the first insert).
 *  - AUTOINCREMENT -> GENERATED BY DEFAULT AS IDENTITY.
 *  - Timestamp-bearing columns the app COMPARES (due, review_date, last_review,
 *    started_at, finished_at, day, last_studied) stay `text` holding ISO-8601
 *    'Z' strings. ISO-8601 sorts lexicographically = chronologically, so the
 *    app's "due < boundary" string comparisons keep working unchanged.
 *  - FTS5 -> a `search_text` column (lower + unaccent, kept by trigger) with a
 *    GIN pg_trgm index, for accent-insensitive substring/prefix search.
 *
 * Idempotent: safe to run repeatedly (CREATE ... IF NOT EXISTS everywhere).
 * Run via `npm run db:init`, NOT on every request.
 */

// ISO-8601 'Z' default for new timestamp columns, matching new Date().toISOString().
const ISO_NOW = `to_char((now() at time zone 'utc'), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')`;

const DDL = `
CREATE EXTENSION IF NOT EXISTS unaccent;
CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE TABLE IF NOT EXISTS subjects (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        text NOT NULL UNIQUE,
  created_at  timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS topics (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subject_id  integer NOT NULL REFERENCES subjects(id) ON DELETE CASCADE,
  name        text NOT NULL,
  file_path   text,
  "order"     integer DEFAULT 0,
  created_at  timestamptz DEFAULT now(),
  UNIQUE (subject_id, name)
);

CREATE TABLE IF NOT EXISTS cards (
  id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  topic_id     integer NOT NULL REFERENCES topics(id) ON DELETE CASCADE,
  question     text NOT NULL,
  answer       text NOT NULL,
  bizu         text,
  source       text,
  tags         text DEFAULT '',
  card_type    text DEFAULT 'normal',
  search_text  text,
  created_at   timestamptz DEFAULT now(),
  UNIQUE (topic_id, question)
);

CREATE TABLE IF NOT EXISTS card_states (
  card_id         integer PRIMARY KEY REFERENCES cards(id) ON DELETE CASCADE,
  stability       double precision DEFAULT 0,
  difficulty      double precision DEFAULT 0,
  due             text NOT NULL DEFAULT ${ISO_NOW},
  elapsed_days    double precision DEFAULT 0,
  scheduled_days  double precision DEFAULT 0,
  reps            integer DEFAULT 0,
  lapses          integer DEFAULT 0,
  last_review     text,
  suspended       integer NOT NULL DEFAULT 0,
  state           text NOT NULL DEFAULT 'new',
  learning_step   integer NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS review_log (
  id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  card_id         integer NOT NULL REFERENCES cards(id) ON DELETE CASCADE,
  rating          integer NOT NULL,
  review_date     text DEFAULT ${ISO_NOW},
  elapsed_days    double precision,
  scheduled_days  double precision,
  stability       double precision,
  difficulty      double precision
);

CREATE TABLE IF NOT EXISTS topic_study (
  topic_id      integer PRIMARY KEY REFERENCES topics(id) ON DELETE CASCADE,
  priority      integer NOT NULL DEFAULT 3,
  study_count   integer NOT NULL DEFAULT 0,
  interval_days double precision NOT NULL DEFAULT 0,
  due           text,
  last_studied  text,
  avg_minutes   double precision,
  min_per_card  double precision,
  status        text NOT NULL DEFAULT 'new',
  created_at    timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS topic_sessions (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  topic_id    integer NOT NULL REFERENCES topics(id) ON DELETE CASCADE,
  day         text,
  started_at  text,
  finished_at text,
  minutes     double precision,
  rep_number  integer
);

CREATE TABLE IF NOT EXISTS daily_plan (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  day         text NOT NULL,
  topic_id    integer NOT NULL REFERENCES topics(id) ON DELETE CASCADE,
  kind        text NOT NULL,
  est_minutes double precision,
  position    integer,
  done        integer NOT NULL DEFAULT 0,
  UNIQUE (day, topic_id)
);

CREATE TABLE IF NOT EXISTS daily_budget (
  day     text PRIMARY KEY,
  minutes double precision
);

-- Performance indexes.
CREATE INDEX IF NOT EXISTS idx_topics_subject       ON topics(subject_id);
CREATE INDEX IF NOT EXISTS idx_cards_topic          ON cards(topic_id);
CREATE INDEX IF NOT EXISTS idx_cards_type           ON cards(card_type);
CREATE INDEX IF NOT EXISTS idx_reviewlog_card       ON review_log(card_id);
CREATE INDEX IF NOT EXISTS idx_cardstates_due_raw   ON card_states(due);
CREATE INDEX IF NOT EXISTS idx_reviewlog_datestr    ON review_log(left(review_date, 10));
CREATE INDEX IF NOT EXISTS idx_topicstudy_due       ON topic_study(due);
CREATE INDEX IF NOT EXISTS idx_topicstudy_status    ON topic_study(status);
CREATE INDEX IF NOT EXISTS idx_dailyplan_day        ON daily_plan(day);
CREATE INDEX IF NOT EXISTS idx_topicsessions_topic  ON topic_sessions(topic_id);
CREATE INDEX IF NOT EXISTS idx_topicsessions_finished ON topic_sessions(finished_at);

-- Accent-insensitive substring search (replaces SQLite FTS5).
CREATE OR REPLACE FUNCTION cards_set_search_text() RETURNS trigger AS $fn$
BEGIN
  NEW.search_text := unaccent(lower(
    coalesce(NEW.question, '') || ' ' ||
    coalesce(NEW.answer,   '') || ' ' ||
    coalesce(NEW.bizu,     '') || ' ' ||
    coalesce(NEW.tags,     '')
  ));
  RETURN NEW;
END;
$fn$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_cards_search ON cards;
CREATE TRIGGER trg_cards_search
  BEFORE INSERT OR UPDATE ON cards
  FOR EACH ROW EXECUTE FUNCTION cards_set_search_text();

CREATE INDEX IF NOT EXISTS idx_cards_search_trgm
  ON cards USING gin (search_text gin_trgm_ops);
`;

export async function initSchema(): Promise<void> {
  // The HTTP fetch path can't run multi-statement SQL (it always prepares a
  // statement). A real WebSocket client uses the simple-query protocol, which
  // accepts the whole multi-statement DDL at once — and keeps the plpgsql
  // function's dollar-quoted body intact (no fragile split-on-semicolon).
  const client = await getPool().connect();
  try {
    await client.query(DDL);
  } finally {
    client.release();
  }
}
